server:
  port: 18888

spring:
  application:
    name: spring-web
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    default-property-inclusion: non_null
    mapper:
      accept_case_insensitive_properties: true
    deserialization:
      fail-on-unknown-properties: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'


